### ISSUE TITLE
lost urls of some tabs after restart

### ISSUE THREAD

**Issue by cn-tools** [arosendorff/tabstop#1]
THX for this great addon!!!

since a few weeks ago and after an update of Google Chrome browser, i notice that i lost some urls in tabs.

![image](https://user-images.githubusercontent.com/6672343/33111827-4f62bf44-cf50-11e7-901e-ab3eb8c0d374.png)
In the screenshot you can see there are some tabs with colored icon. These are the tabs, where i lost the urls. If i click one of them, it looks like the active tab in the screenshot. Sometimes i can find the url with help of tab history, but not every time.

I can reproduce this issue on some systems:
Windows 10 64Bit and Google Chrome Version 62.0.3202.94 (Offizieller Build) (64-Bit)
Windows 10 32Bit and Google Chrome Version 62.0.3202.94 (Offizieller Build) (32-Bit)

**Comment by arosendorff** [comment]
I have updated the extension to version 2.0. Please make sure you have it installed and that the issue has been resolved, as I seem unable to replicate it on my side.

**Comment by cn-tools** [comment]
@arosendorff sorry for my late respoonse :/

I still have the problem on Win10 64Bit and Google Chrome Version 62.0.3202.94 (Offizieller Build) (64-Bit).
I have not tried it since the last time on Win10 32Bit.
